# Functions in this module assign a numerical value to
# each of the MPAA rating categories that appear on the dataset.
# The idea is to create a dictionary where the keys are the
# names of the MPAA rating categories and the values assigned
# to the keys are the average revenue generated by movies with that rating.
import creatingDictionary
dataset=creatingDictionary.test()
def populate():
    '''
    This function creates a dictionary by traversing the input
    dataset which is a list of dictionaries. For every new value
    of MPAA rating it finds , the function creates a dictionary
    entry with key the MPAA rating and value zero. This dictionary
    is returned once the for loop is completed.
    '''
    mpaaDictionary={}
    for film in dataset:
        if not(film['Rated'] in mpaaDictionary):
            mpaaDictionary[film['Rated']]=0
    return mpaaDictionary

def assignCount():
    '''
    This fucntion calls the populate() function and stores its
    return value (the dictionary with the mpaa ratings as keys
    and assigned values all zero). The values are updated from zero to
    the number of films with that rating by using a for loop to traverse
    the original input dataset.
    '''
    mpaaDictionary=populate()
    count=0
    for film in dataset:
        if (film['Rated'] in mpaaDictionary):
            mpaaDictionary[film['Rated']]+=1



    return mpaaDictionary

def assignTotalRevenue():
    '''
    This fucntion calls the populate() function and stores its
    return value (the dictionary with the mpaa ratings as keys
    and assigned values all zero). The values are updated from zero to
    the total revenue generated by films with that rating
    by using a for loop to traverse the original input dataset.
    '''
    mpaaDictionary=populate()
    count=0
    for film in dataset:
        if (film['Rated'] in mpaaDictionary):
            mpaaDictionary[film['Rated']]+=float(film['BoxOffice'])



    return mpaaDictionary

def assignAverageRevenue():
    '''
    This function calls all the three previous functions and stores
    their return values in three separate variables. Then the values in
    the mpaaAverage dictionary (the dictionary returned by the populate
    function) are updated from zero to the average revenue generated by the
    films with the mpaarating.( The keys are the mpaa ratings).
    '''
    mpaaTotal=assignTotalRevenue()
    mpaaCount=assignCount()
    mpaaAverage=populate()
    for mpaa in mpaaAverage:
        mpaaAverage[mpaa]=mpaaTotal[mpaa]/mpaaCount[mpaa]

    return mpaaAverage






    



    
