#This module is for assigning ratings for the production houses
#so that they can be represented by numerical values. So that
# we can use them in the regression model
import creatingDictionary
dataset=creatingDictionary.test()
def populate():
    '''
    The output of this function is a dictionary which has
    as keys the names of production houses that appear in
    the dataset. The values assigned to the keys are all zero.
    '''
    productionDictionary={}
    for film in dataset:
        if not(film['Production'] in productionDictionary):
            productionDictionary[film['Production']]=0
    return productionDictionary

def assignCount():
    '''
    The output of this function is the dictionary in which
    the keys - the names of the production houses and
    the value - number of occurrences in the dataset. ie the number
    of films in the dataset that the producion house has produced.
    '''
    productionDictionary=populate()
    count=0
    for film in dataset:
        if (film['Production'] in productionDictionary):
            productionDictionary[film['Production']]+=1



    return productionDictionary

def assignTotalRevenue():
    '''
    The function returns a dictionary in which
    the keys - the names of the produciton houses(that appear in the dataset)
    the values - the total revenue generrated by the films produced by them
    (only the films present in the dataset are considered here
    '''
    productionDictionary=populate()
    count=0
    for film in dataset:
        if (film['Production'] in productionDictionary):
            productionDictionary[film['Production']]+=float(film['BoxOffice'])



    return productionDictionary

def assignAverageRevenue():
    '''
    This function creates the dictionary with
    keys - the names of the production houses
    values - the average revenue generated by films produced by these
    production houses.
    This function uses the previous two function in this module viz
    assignCount() and assignTotalRevenue() to accomplish this.
    '''
    productionTotal=assignTotalRevenue()
    productionCount=assignCount()
    productionAverage=populate()
    for production in productionAverage:
        productionAverage[production]=productionTotal[production]/productionCount[production]

    return productionAverage






    



    
